version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fit-coach-dev

    ports:
      - "3307:3306"  # Use port 3307 on the host
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    image: fit-coach-app
    container_name: fit-coach-app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/fit-coach-dev?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
