spring.application.name: fit-coach

spring:
  datasource:
    url: jdbc:h2:mem:krasnopolskyi-gym
    username: maks
    password:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2



logging:
  level:
    root: INFO
  pattern:
    config: /logback-spring.xml

token:
  signing:
    key: SW1hZ2luYXRpb24gaXMgbW9yZSBpbXBvcnRhbnQgdGhhbiBrbm93bGVkZ2Uu
