name: Gradle Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ensure gradlew has execute permissions
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Run Gradle tests
      - name: Run Tests
        run: ./gradlew test
